server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes: #网关路由配置

#        #UserService
#        - id: user-service #路由id，自定义，只要唯一即可
#          #uri: localhost://127.0.0.1/8081 路由的目标地址，http就是固定地址
#          uri: lb://userService # 路由的目标地址 lb就是负载均衡LoadBalanced，后面跟服务名称
#          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
#            - Path=/user/**  # 这个是按照路径匹配，只要以/user/开头就符号要求
#          filters:
#            - AddRequestHeader=Service,User

        # LoginService
        - id: login-service
          uri: lb://loginService
          predicates:
            - Path=/employee/**
          filters:
            - AddRequestHeader=Service,Employee
        # UserService
        - id: user-service
          uri: lb://userService
          predicates:
            - Path=/user/**,/common/**
          filters:
            - AddRequestHeader=Service,User
        # AnimalService
        - id: animal-service
          uri: lb://animalService
          predicates:
            - Path=/animal/**
          filters:
            - AddRequestHeader=Service,Animal
        # AdoptService
        - id: adopt-service
          uri: lb://adoptService
          predicates:
            - Path=/adopt/**
          filters:
            - AddRequestHeader=Service,Adopt
        # ExamineService
        - id: examine-service
          uri: lb://examineService
          predicates:
            - Path=/examine/**
          filters:
            - AddRequestHeader=Service,Examine

      default-filters:
        - AddRequestHeader=Common,Test
#      globalcors: #全局的跨域处理
#        add-to-simple-url-handler-mapping: true # 解决浏览器进行跨越询问OPTIONS请求
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: # 允许哪些网站的跨域请求
#              - "http://localhost:80"
#            allowedMethods: # 允许的跨域AJAX的请求方式
#              - "GET"
#              - "POST"
#              - "DELETE"
#              - "PUT"
#              - "OPTIONS"
#            allowedHeaders: "*" # 允许在请求中携带的头信息
#            allowCredentials: true # 是否允许携带Cookie
#            maxAge: 360000 # 这次跨域检测的有效期
#################