server:
  port: 8040
####################
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sams?charsetEncoding=UTF-8&useSSL=false&useServerPrepStmts=true&cachePrepStmts=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  application:
    name: examineService
  cloud:
    nacos: #nacos配置
      discovery:
        server-addr: localhost:8848 #nacos服务地址
        cluster-name: SH  #集群名称
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 8 #最大连接数
        max-wait: 1ms #连接池最大阻塞等待时间
        max-idle: 4 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接
  cache:
    redis:
      time-to-live: 1800000
logging:
  level:
    org.project: debug
  pattern:
    dateformat: YYYY-MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka/
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    #    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
#########################
adoptService: #为animal微服务配置IRUle负载均衡模式
  ribbon: #Ribbon负载均衡
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule #nacos集群负载均衡，以集群为单位，单位内随机选择相同服务
userService:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
animalService:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
ribbon: #负载均衡配置
  eager-load: #饥饿加载
    enabled: true
    clients: # 饥饿加载配置微服务列表
      - adoptService
      - userService
      - animalService
########################
save_path: C:\Users\13093\Desktop\Projects\nginx-1.25.4\html\backend\images\examine\